import type { Prisma, Team as TeamRow } from '../../../generated/prisma/client';
import {
	bikeTypeFromDb,
	bikeTypeToDb,
	clubTypeFromDb,
	clubTypeToDb,
	disciplineFromDb,
	disciplineToDb,
	dropPolicyFromDb,
	dropPolicyToDb,
	formatFromDb,
	formatToDb,
	rankingSystemFromDb,
	rankingSystemToDb,
	segmentationFromDb,
	segmentationToDb,
} from '../teamEnums';
import type { Team, TeamFormValues } from '../types';
import type { CreateTeamInput } from '../validation';

function nonEmpty<T>(items: T[]): T[] | undefined {
	return items.length > 0 ? items : undefined;
}

export function toTeam(row: TeamRow): Team {
	return {
		id: row.id,
		name: row.name,
		type: clubTypeFromDb[row.type],
		missionStatement: row.missionStatement ?? undefined,
		codeOfConduct: row.codeOfConduct ?? undefined,
		affiliation: row.affiliation ?? undefined,
		location: row.location,
		additionalLocations: nonEmpty(row.additionalLocations),
		founded: row.founded ?? 0,
		visibility: row.visibility,
		contact: {
			phone: row.contactPhone ?? undefined,
			email: row.contactEmail ?? undefined,
		},
		primaryLanguage: row.primaryLanguage ?? undefined,
		verified: row.verified,
		lastActiveYear: row.lastActiveYear ?? 0,
		bikeType: bikeTypeFromDb[row.bikeType],
		discipline: row.discipline ? disciplineFromDb[row.discipline] : undefined,
		eBikeAllowed: row.eBikeAllowed,
		format: formatFromDb[row.format],
		virtualPlatform: row.virtualPlatforms[0],
		homeBaseAffiliation: row.homeBaseAffiliation ?? undefined,
		website: row.website ?? undefined,
		social: {
			instagram: row.instagram ?? undefined,
			facebook: row.facebook ?? undefined,
			strava: row.strava ?? undefined,
			discord: row.discord ?? undefined,
		},
		ageRequirement:
			row.ageMin !== null || row.ageMax !== null ?
				{ min: row.ageMin ?? undefined, max: row.ageMax ?? undefined }
			:	undefined,
		personaRestrictions: nonEmpty(row.personaRestrictions),
		memberCount: row.memberCount,
		memberLimit: row.memberLimit ?? undefined,
		waitlist: row.waitlist,
		howToJoin: row.howToJoin ?? '',
		rideSchedule: row.rideSchedule ?? 'Weekly',
		startTimes: nonEmpty(row.startTimes),
		pace: row.pace ?? 'Casual',
		segmentation: row.segmentation ? segmentationFromDb[row.segmentation] : 'N/A',
		typicalDistanceMiles: row.typicalDistanceMiles ?? 0,
		typicalElevationGainFt: row.typicalElevationGainFt ?? 0,
		dropPolicy: row.dropPolicy ? dropPolicyFromDb[row.dropPolicy] : 'No-drop',
		rideVisibility: row.rideVisibility,
		competitiveOrCasual: row.competitiveOrCasual,
		skillLevel: row.skillLevel,
		instructional: row.instructional,
		duesRequired: row.duesRequired,
		duesAmount: row.duesAmount ?? undefined,
		duesSchedule: row.duesSchedule ?? undefined,
		requiredRides: row.requiredRides,
		requiredRaces: row.requiredRaces ?? undefined,
		mileageRequirement:
			row.mileageMin !== null && row.mileageFrequency !== null ?
				{ min: row.mileageMin, frequency: row.mileageFrequency }
			:	undefined,
		requiredKit: row.requiredKit,
		rankingSystem: rankingSystemFromDb[row.rankingSystem],
		hasRoster: row.hasRoster,
		sponsors: nonEmpty(row.sponsors),
		eventTypes: nonEmpty(row.eventTypes),
		joinRequirements: {
			tryouts: row.joinTryouts,
			referralRequired: row.joinReferral,
			inviteOnly: row.joinInviteOnly,
			open: row.joinOpen,
		},
		tags: row.tags,
	};
}

export function toTeamCreateInput(
	input: CreateTeamInput,
	submittedById?: number,
): Prisma.TeamCreateInput {
	return {
		status: 'Pending',
		submittedBy: submittedById ? { connect: { id: submittedById } } : undefined,
		name: input.name,
		type: clubTypeToDb[input.type],
		missionStatement: input.missionStatement,
		codeOfConduct: input.codeOfConduct,
		affiliation: input.affiliation,
		location: input.location,
		additionalLocations: input.additionalLocations ?? [],
		founded: input.founded,
		visibility: input.visibility,
		primaryLanguage: input.primaryLanguage,
		contactPhone: input.contactPhone,
		contactEmail: input.contactEmail,
		bikeType: bikeTypeToDb[input.bikeType],
		discipline: input.discipline ? disciplineToDb[input.discipline] : undefined,
		eBikeAllowed: input.eBikeAllowed,
		format: formatToDb[input.format],
		virtualPlatforms: input.virtualPlatforms ?? [],
		homeBaseAffiliation: input.homeBaseAffiliation,
		website: input.website,
		instagram: input.instagram,
		facebook: input.facebook,
		strava: input.strava,
		discord: input.discord,
		ageMin: input.ageMin,
		ageMax: input.ageMax,
		personaRestrictions: input.personaRestrictions ?? [],
		memberCount: input.memberCount,
		memberLimit: input.memberLimit,
		waitlist: input.waitlist,
		howToJoin: input.howToJoin,
		rideSchedule: input.rideSchedule,
		startTimes: input.startTimes ?? [],
		pace: input.pace,
		segmentation: input.segmentation ? segmentationToDb[input.segmentation] : undefined,
		typicalDistanceMiles: input.typicalDistanceMiles,
		typicalElevationGainFt: input.typicalElevationGainFt,
		dropPolicy: input.dropPolicy ? dropPolicyToDb[input.dropPolicy] : undefined,
		rideVisibility: input.rideVisibility,
		competitiveOrCasual: input.competitiveOrCasual,
		skillLevel: input.skillLevel,
		instructional: input.instructional,
		duesRequired: input.duesRequired,
		duesAmount: input.duesAmount,
		duesSchedule: input.duesSchedule,
		requiredRides: input.requiredRides,
		requiredRaces: input.requiredRaces,
		mileageMin: input.mileageMin,
		mileageFrequency: input.mileageFrequency,
		requiredKit: input.requiredKit,
		rankingSystem: input.rankingSystem ? rankingSystemToDb[input.rankingSystem] : undefined,
		hasRoster: input.hasRoster,
		sponsors: input.sponsors ?? [],
		eventTypes: input.eventTypes ?? [],
		joinTryouts: input.joinTryouts,
		joinReferral: input.joinReferral,
		joinInviteOnly: input.joinInviteOnly,
		joinOpen: input.joinOpen,
	};
}

const PERSONA_CODE_BY_LABEL: Record<string, string> = {
	'Women Only': 'womenOnly',
	'Men Only': 'menOnly',
	'LGBT Only': 'lgbtOnly',
};

export function toTeamFormValues(row: TeamRow): TeamFormValues {
	const persona = row.personaRestrictions[0];
	const personaCode =
		persona ? (PERSONA_CODE_BY_LABEL[persona] ?? 'other') : null;

	return {
		name: row.name,
		type: clubTypeFromDb[row.type],
		missionStatement: row.missionStatement ?? '',
		codeOfConduct: row.codeOfConduct ?? '',
		affiliation: row.affiliation ?? '',
		location: row.location,
		additionalLocations: row.additionalLocations,
		founded: row.founded?.toString() ?? '',
		visibility: row.visibility,
		primaryLanguage: row.primaryLanguage ?? '',
		contactPhone: row.contactPhone ?? '',
		contactEmail: row.contactEmail ?? '',
		bikeType: bikeTypeFromDb[row.bikeType],
		format: formatFromDb[row.format],
		virtualPlatform: row.virtualPlatforms,
		homeBaseAffiliation: row.homeBaseAffiliation ?? '',
		website: row.website ?? '',
		instagram: row.instagram ?? '',
		facebook: row.facebook ?? '',
		strava: row.strava ?? '',
		discord: row.discord ?? '',
		ageMin: row.ageMin?.toString() ?? '',
		ageMax: row.ageMax?.toString() ?? '',
		memberCount: row.memberCount.toString(),
		memberLimit: row.memberLimit?.toString() ?? '',
		howToJoin: row.howToJoin ?? '',
		personaRestriction: personaCode,
		personaOtherDescription: personaCode === 'other' ? (persona ?? '') : '',
		eBikeAllowed: row.eBikeAllowed,
		waitlist: row.waitlist,
		competitiveOrCasual: row.competitiveOrCasual,
		skillLevel: row.skillLevel,
		duesAmount: row.duesAmount ?? '',
		duesSchedule: row.duesSchedule ?? 'Annually',
		requiredRaces: row.requiredRaces?.toString() ?? '',
		mileageMin: row.mileageMin?.toString() ?? '',
		mileageFrequency: row.mileageFrequency ?? 'Monthly',
		rankingSystem: rankingSystemFromDb[row.rankingSystem],
		sponsors: row.sponsors.join(', '),
		instructional: row.instructional,
		duesRequired: row.duesRequired,
		requiredRides: row.requiredRides,
		requiredKit: row.requiredKit,
		hasRoster: row.hasRoster,
		eventSponsor: row.eventTypes.includes('Sponsor Events'),
		eventTeamSpecific: row.eventTypes.includes('Team-specific Events'),
		eventPublic: row.eventTypes.includes('Public Events'),
		eventRecruiting: row.eventTypes.includes('Recruiting Events'),
		joinTryouts: row.joinTryouts,
		joinReferral: row.joinReferral,
		joinInviteOnly: row.joinInviteOnly,
		joinOpen: row.joinOpen,
	};
}

export function toApprovedTeamUpdate(
	input: CreateTeamInput,
): Prisma.TeamUpdateManyMutationInput {
	return {
		status: 'Approved',
		name: input.name,
		type: clubTypeToDb[input.type],
		missionStatement: input.missionStatement ?? null,
		codeOfConduct: input.codeOfConduct ?? null,
		affiliation: input.affiliation ?? null,
		location: input.location,
		additionalLocations: input.additionalLocations ?? [],
		founded: input.founded ?? null,
		visibility: input.visibility ?? 'Public',
		primaryLanguage: input.primaryLanguage ?? null,
		contactPhone: input.contactPhone ?? null,
		contactEmail: input.contactEmail ?? null,
		bikeType: bikeTypeToDb[input.bikeType],
		eBikeAllowed: input.eBikeAllowed ?? false,
		format: formatToDb[input.format],
		virtualPlatforms: input.virtualPlatforms ?? [],
		homeBaseAffiliation: input.homeBaseAffiliation ?? null,
		website: input.website ?? null,
		instagram: input.instagram ?? null,
		facebook: input.facebook ?? null,
		strava: input.strava ?? null,
		discord: input.discord ?? null,
		ageMin: input.ageMin ?? null,
		ageMax: input.ageMax ?? null,
		personaRestrictions: input.personaRestrictions ?? [],
		memberCount: input.memberCount ?? 0,
		memberLimit: input.memberLimit ?? null,
		waitlist: input.waitlist ?? false,
		howToJoin: input.howToJoin ?? null,
		competitiveOrCasual: input.competitiveOrCasual,
		skillLevel: input.skillLevel,
		instructional: input.instructional ?? false,
		duesRequired: input.duesRequired ?? false,
		duesAmount: input.duesAmount ?? null,
		duesSchedule: input.duesSchedule ?? null,
		requiredRides: input.requiredRides ?? false,
		requiredRaces: input.requiredRaces ?? null,
		mileageMin: input.mileageMin ?? null,
		mileageFrequency: input.mileageFrequency ?? null,
		requiredKit: input.requiredKit ?? false,
		rankingSystem: input.rankingSystem ? rankingSystemToDb[input.rankingSystem] : 'NA',
		hasRoster: input.hasRoster ?? false,
		sponsors: input.sponsors ?? [],
		eventTypes: input.eventTypes ?? [],
		joinTryouts: input.joinTryouts ?? false,
		joinReferral: input.joinReferral ?? false,
		joinInviteOnly: input.joinInviteOnly ?? false,
		joinOpen: input.joinOpen ?? false,
	};
}
