export const TAG_OPTIONS: string[] = [
	'100 miles',
	'20 miles',
	'40 miles',
	'50+',
	'60 miles',
	'60+',
	'accessible',
	'adaptive',
	'adventure',
	'advocacy',
	'african american',
	'after work',
	'all abilities',
	'all weather',
	'alleycat',
	'altitude',
	'amateur',
	'arabic',
	'asian american',
	'asl-friendly',
	'association',
	'backroads',
	'base miles',
	'beginner',
	'beginner-friendly',
	'beginners',
	'bike build',
	'bike coop',
	'bike kitchen',
	'bike lanes',
	'bike library',
	'bike night',
	'bike paths',
	'bike polo',
	'bike repair',
	'bike safety',
	'bikepacking',
	'bilingual',
	'bipoc',
	'black',
	'black cyclists',
	'bmx',
	'brevet',
	'brewery',
	'brewery rides',
	'california',
	'canyon',
	'cargo bike',
	'casual',
	'cat 1',
	'cat 1-3',
	'cat 2',
	'cat 3',
	'cat 4',
	'cat 4-5',
	'cat 5',
	'century ride',
	'charity',
	'chill',
	'city',
	'city bike',
	'classic bikes',
	'climbing',
	'club',
	'club kit',
	'co-ed',
	'coached',
	'coaching',
	'coastal',
	'coffee',
	'coffee ride',
	'college',
	'collegiate',
	'colorado',
	'community',
	'community ride',
	'commuter',
	'commuter bike',
	'competitive',
	'conversational pace',
	'couples',
	'criterium',
	'cross-country',
	'cx',
	'cx bike',
	'cycle ball',
	'cycling academy',
	'cyclo-tourist',
	'cyclocross',
	'dads',
	'desert',
	'development',
	'development team',
	'dirt jump',
	'dirt roads',
	'downhill',
	'drop ride',
	'duathlon',
	'e-bike',
	'e-mtb',
	'e-sports',
	'early-morning',
	'earn-a-bike',
	'east coast',
	'echelon',
	'educational',
	'electric',
	'elite',
	'endurance',
	'endurance pace',
	'enduro',
	'english',
	'ergo',
	'esports',
	'evening',
	'faith-based',
	'family-friendly',
	'farmland',
	'fast',
	'fat bike',
	'fat tire',
	'feeder team',
	'first responders',
	'fixed-gear',
	'fixie',
	'flat',
	'flat roads',
	'flowy',
	'folding bike',
	'food',
	'forest',
	'freeride',
	'french',
	'ftp',
	'full-suspension',
	'fundraising',
	'gear swaps',
	'german',
	'gran fondo',
	'gravel',
	'gravel bike',
	'gravel roads',
	'great plains',
	'greenway',
	'group rides',
	'group training',
	'group workouts',
	'hammer',
	'handcycle',
	'hardtail',
	'high school',
	'hill climb',
	'hill repeats',
	'hills',
	'hilly',
	'hindi',
	'inclusive',
	'indoor',
	'instructional',
	'intervals',
	'japanese',
	'junior',
	'junior team',
	'juniors',
	'kids',
	'kids-ok',
	'kit',
	'kom',
	'kom-hunting',
	'korean',
	'lake',
	'latino',
	'league',
	'lgbt',
	'lgbtq',
	'long rides',
	'long-distance',
	'loops',
	'low-impact',
	'lunch ride',
	'maintenance clinics',
	'mandarin',
	'masters',
	'masters team',
	'men',
	'mid-atlantic',
	'midwest',
	'mixed terrain',
	'moms',
	'mountain bike',
	'mountain biking',
	'mountain west',
	'mountains',
	'mtb',
	'mud',
	'multi-day',
	'national forest',
	'new england',
	'newcomers',
	'nica',
	'night rides',
	'night-rides',
	'no-drop',
	'nonbinary-friendly',
	'nonprofit',
	'northeast',
	'online',
	'open water',
	'orchards',
	'out-and-back',
	'overnight',
	'paceline',
	'pacific northwest',
	'parents',
	'paved paths',
	'pedal assist',
	'point-to-point',
	'portuguese',
	'post-ride beers',
	'pro-am',
	'professionals',
	'pub ride',
	'pump track',
	'qom',
	'qom-hunting',
	'race prep',
	'race support',
	'race team',
	'racing',
	'rail trail',
	'randonneuring',
	'recumbent',
	'relaxed',
	'retro',
	'returning riders',
	'ride captains',
	'ride leaders',
	'river',
	'road',
	'road bike',
	'rocky',
	'rolling hills',
	'rouvy',
	'rural',
	'sand',
	'saturday',
	'scenic',
	'school',
	'seniors',
	'series',
	'shop ride',
	'short rides',
	'sightseeing',
	'single-speed',
	'singletrack',
	'skills clinics',
	'slopestyle',
	'smooth',
	'snow',
	'social',
	'southeast',
	'southwest',
	'spanish-speaking',
	'sponsored',
	'sprints',
	'state park',
	'steel bikes',
	'strava',
	'structured',
	'structured-training',
	'student',
	'suburban',
	'summer',
	'sunday',
	'sunrise',
	'tandem',
	'team',
	'team kit',
	'tech industry',
	'technical',
	'teens',
	'tempo',
	'texas',
	'time trial',
	'touring',
	'track',
	'track nights',
	'trail',
	'trails',
	'trainer',
	'trainerroad',
	'training',
	'trans-inclusive',
	'tri',
	'tri bike',
	'triathlon',
	'trike',
	'tt practice',
	'uci',
	'ultra-distance',
	'uniform',
	'university',
	'urban',
	'usa cycling',
	'usac',
	'velodrome',
	'veterans',
	'vietnamese',
	'vineyards',
	'vintage',
	'virtual',
	'virtual racing',
	'virtual-plus-irl',
	'visually impaired',
	'volunteer',
	'watts',
	'weekend',
	'weeknight',
	'weeknight rides',
	'welcoming',
	'west coast',
	'wildlife',
	'wind',
	'winter',
	'winter-training',
	'women',
	'women only',
	"women's",
	"women's team",
	'workplace',
	'year-round',
	'ymca',
	'youth',
	'zone 1',
	'zone 2',
	'zone 3',
	'zone 4',
	'zone 5',
	'zwift',
];

export const MAX_TAGS = 10;

const TAG_PATTERN = /^[a-z0-9][a-z0-9+&'-]*( [a-z0-9][a-z0-9+&'-]*)?$/;
const MAX_TAG_LENGTH = 40;

export function normalizeTag(value: string): string {
	return value.trim().toLowerCase().replace(/\s+/g, ' ');
}

export function isValidTag(tag: string): boolean {
	return tag.length <= MAX_TAG_LENGTH && TAG_PATTERN.test(tag);
}
