import type {
  BikeType,
  ClubType,
  DropPolicy,
  Format,
  MtbDiscipline,
  Pace,
  ScheduleFrequency,
  Segmentation,
  SkillLevel,
  Team,
} from "./types";

interface TeamInput {
  id: string;
  name: string;
  type: ClubType;
  location: string;
  founded: number;
  bikeType: BikeType;
  format: Format;
  pace: Pace;
  skillLevel: SkillLevel;
  competitiveOrCasual: "Competitive" | "Casual";
  memberCount: number;
  typicalDistanceMiles: number;
  typicalElevationGainFt: number;
  dropPolicy: DropPolicy;
  rideSchedule: ScheduleFrequency;
  segmentation: Segmentation;
  howToJoin: string;
  tags: string[];
  missionStatement?: string;
  overrides?: Partial<Team>;
}

function makeTeam(input: TeamInput): Team {
  const { overrides, skillLevel, ...rest } = input;
  return {
    ...rest,
    skillLevels: [skillLevel],
    visibility: "Public",
    rideVisibility: "Public",
    verified: true,
    lastActiveYear: 2026,
    eBikeAllowed: input.bikeType === "E-bike",
    waitlist: false,
    instructional: false,
    duesRequired: false,
    requiredRides: false,
    requiredKit: false,
    hasRoster: true,
    primaryLanguage: "English",
    contact: { email: `hello@${input.id.replace(/-/g, "")}.club` },
    social: {},
    joinRequirements: {
      tryouts: false,
      referralRequired: false,
      inviteOnly: false,
      open: true,
    },
    ...overrides,
  };
}

export const teams: Team[] = [
  makeTeam({
    id: "portland-velo-collective",
    name: "Portland Velo Collective",
    type: "Club",
    location: "Portland, OR",
    founded: 2014,
    bikeType: "Road",
    format: "In-person",
    pace: "Steady",
    skillLevel: "Intermediate",
    competitiveOrCasual: "Casual",
    memberCount: 145,
    typicalDistanceMiles: 32,
    typicalElevationGainFt: 1200,
    dropPolicy: "No-drop",
    rideSchedule: "Weekly",
    segmentation: "N/A",
    howToJoin: "Show up to any Tuesday or Saturday ride, no sign-up required.",
    tags: ["road", "social", "no-drop", "weeknight rides", "beginner-friendly"],
    missionStatement:
      "Keep Portland's road riding scene welcoming, low-ego, and fun regardless of pace.",
    overrides: {
      startTimes: ["Tue 6:00 PM", "Sat 8:00 AM"],
      website: "https://portlandvelo.example.org",
      social: { instagram: "@portlandvelo", strava: "Portland Velo Collective" },
      eventTypes: ["Public Events"],
    },
  }),

  makeTeam({
    id: "mile-high-gravel-grinders",
    name: "Mile High Gravel Grinders",
    type: "Group Ride",
    location: "Denver, CO",
    founded: 2018,
    bikeType: "Gravel",
    format: "In-person",
    pace: "Casual",
    skillLevel: "Beginner",
    competitiveOrCasual: "Casual",
    memberCount: 89,
    typicalDistanceMiles: 28,
    typicalElevationGainFt: 1800,
    dropPolicy: "No-drop",
    rideSchedule: "Weekly",
    segmentation: "N/A",
    howToJoin: "Join our Strava club and RSVP to the Sunday route.",
    tags: ["gravel", "beginner-friendly", "dirt roads", "social"],
    missionStatement: "Get more people comfortable riding dirt, one gentle Sunday at a time.",
    overrides: {
      instructional: true,
      social: { strava: "Mile High Gravel Grinders" },
      eventTypes: ["Public Events"],
    },
  }),

  makeTeam({
    id: "austin-crit-racing-team",
    name: "Austin Crit Racing Team",
    type: "Team",
    location: "Austin, TX",
    founded: 2011,
    bikeType: "Road",
    format: "In-person",
    pace: "Competitive",
    skillLevel: "Advanced",
    competitiveOrCasual: "Competitive",
    memberCount: 42,
    typicalDistanceMiles: 45,
    typicalElevationGainFt: 900,
    dropPolicy: "Drop",
    rideSchedule: "Weekly",
    segmentation: "A Group",
    howToJoin: "Applications reviewed each fall; a tryout ride is required.",
    tags: ["road", "racing", "criterium", "competitive"],
    missionStatement: "Field a top-tier crit squad and podium at every regional race on the calendar.",
    overrides: {
      visibility: "Private",
      affiliation: "USA Cycling Club Member",
      codeOfConduct: "Zero tolerance for unsportsmanlike conduct at races or team events.",
      memberLimit: 50,
      waitlist: true,
      duesRequired: true,
      duesAmount: "$150/year",
      duesSchedule: "Annually",
      requiredRides: true,
      requiredRaces: 6,
      mileageRequirement: { min: 150, frequency: "Monthly" },
      requiredKit: true,
      sponsors: ["Lone Star Bikes", "Velocity Nutrition"],
      eventTypes: ["Team-specific Events", "Sponsor Events", "Recruiting Events"],
      joinRequirements: { tryouts: true, referralRequired: false, inviteOnly: false, open: false },
      contact: { email: "captain@austincrit.example.org", phone: "512-555-0142" },
      website: "https://austincrit.example.org",
    },
  }),

  makeTeam({
    id: "front-range-mtb-mavericks",
    name: "Front Range MTB Mavericks",
    type: "Club",
    location: "Boulder, CO",
    founded: 2016,
    bikeType: "MTB",
    format: "In-person",
    pace: "Steady",
    skillLevel: "Intermediate",
    competitiveOrCasual: "Casual",
    memberCount: 76,
    typicalDistanceMiles: 18,
    typicalElevationGainFt: 2400,
    dropPolicy: "No-drop",
    rideSchedule: "Weekly",
    segmentation: "N/A",
    howToJoin: "Come to a Saturday trailhead meetup; helmets and full-suspension recommended.",
    tags: ["mtb", "singletrack", "climbing", "trails"],
    overrides: {
      discipline: "Trail",
      startTimes: ["Sat 9:00 AM"],
      social: { instagram: "@frontrangemtb" },
    },
  }),

  makeTeam({
    id: "cascadia-enduro-collective",
    name: "Cascadia Enduro Collective",
    type: "Team",
    location: "Bend, OR",
    founded: 2017,
    bikeType: "MTB",
    format: "In-person",
    pace: "Competitive",
    skillLevel: "Advanced",
    competitiveOrCasual: "Competitive",
    memberCount: 28,
    typicalDistanceMiles: 12,
    typicalElevationGainFt: 2600,
    dropPolicy: "Drop",
    rideSchedule: "Weekly",
    segmentation: "A Group",
    howToJoin: "Come session Phil's Trail with us on a Thursday before applying; we want to see you ride.",
    tags: ["mtb", "enduro", "racing", "full-suspension", "competitive"],
    missionStatement: "Race enduro at a regional level while keeping Central Oregon's trail community tight-knit.",
    overrides: {
      discipline: "Enduro",
      requiredKit: true,
      social: { instagram: "@cascadiaenduro" },
      eventTypes: ["Team-specific Events", "Public Events"],
    },
  }),

  makeTeam({
    id: "lonestar-track-league",
    name: "Lonestar Track League",
    type: "Team",
    location: "Austin, TX",
    founded: 2009,
    bikeType: "Track",
    format: "In-person",
    pace: "Competitive",
    skillLevel: "Advanced",
    competitiveOrCasual: "Competitive",
    memberCount: 24,
    typicalDistanceMiles: 15,
    typicalElevationGainFt: 0,
    dropPolicy: "Drop",
    rideSchedule: "Weekly",
    segmentation: "A Group",
    howToJoin: "Referral from a current member required; velodrome certification needed.",
    tags: ["track", "velodrome", "racing", "competitive"],
    overrides: {
      requiredKit: true,
      hasRoster: true,
      joinRequirements: { tryouts: false, referralRequired: true, inviteOnly: false, open: false },
      homeBaseAffiliation: "Austin Super Velodrome",
    },
  }),

  makeTeam({
    id: "gulf-coast-triathlon-squad",
    name: "Gulf Coast Triathlon Squad",
    type: "Club",
    location: "Tampa, FL",
    founded: 2015,
    bikeType: "Tri",
    format: "In-person",
    pace: "Steady",
    skillLevel: "Intermediate",
    competitiveOrCasual: "Casual",
    memberCount: 67,
    typicalDistanceMiles: 40,
    typicalElevationGainFt: 300,
    dropPolicy: "No-drop",
    rideSchedule: "Weekly",
    segmentation: "N/A",
    howToJoin: "Sign up for a coached brick workout to meet the group before joining.",
    tags: ["triathlon", "tri", "brick workouts", "coached"],
    overrides: {
      instructional: true,
      duesRequired: true,
      duesAmount: "$40/month",
      duesSchedule: "Monthly",
      social: { instagram: "@gulfcoasttri" },
    },
  }),

  makeTeam({
    id: "velocity-ebike-social-club",
    name: "Velocity E-Bike Social Club",
    type: "Group Ride",
    location: "Sacramento, CA",
    founded: 2021,
    bikeType: "E-bike",
    format: "In-person",
    pace: "Casual",
    skillLevel: "Beginner",
    competitiveOrCasual: "Casual",
    memberCount: 58,
    typicalDistanceMiles: 20,
    typicalElevationGainFt: 400,
    dropPolicy: "No-drop",
    rideSchedule: "Weekly",
    segmentation: "N/A",
    howToJoin: "Message us on Facebook to be added to the next ride.",
    tags: ["e-bike", "accessible", "low-impact", "social"],
    missionStatement: "Prove that e-bikes belong on every group ride: accessible cycling for all ages.",
    overrides: {
      ageRequirement: { min: 18 },
      social: { facebook: "VelocityEBikeSocial" },
      verified: false,
      lastActiveYear: 2023,
    },
  }),

  makeTeam({
    id: "zwift-summit-riders",
    name: "Zwift Summit Riders",
    type: "Team",
    location: "Chicago, IL",
    founded: 2019,
    bikeType: "Road",
    format: "Virtual",
    pace: "Competitive",
    skillLevel: "Advanced",
    competitiveOrCasual: "Competitive",
    memberCount: 310,
    typicalDistanceMiles: 25,
    typicalElevationGainFt: 1500,
    dropPolicy: "Drop",
    rideSchedule: "Weekly",
    segmentation: "A Group",
    howToJoin: "Apply through our Discord and complete a qualifying Zwift race.",
    tags: ["virtual", "zwift", "racing", "esports"],
    overrides: {
      virtualPlatform: "Zwift",
      homeBaseAffiliation: "Zwift Racing League",
      memberLimit: 400,
      requiredKit: true,
      social: { discord: "discord.gg/zwiftsummit" },
      startTimes: ["Mon 7:00 PM", "Thu 7:00 PM"],
    },
  }),

  makeTeam({
    id: "rose-city-womens-cycling",
    name: "Rose City Women's Cycling",
    type: "Club",
    location: "Portland, OR",
    founded: 2017,
    bikeType: "Road",
    format: "In-person",
    pace: "Steady",
    skillLevel: "Intermediate",
    competitiveOrCasual: "Casual",
    memberCount: 120,
    typicalDistanceMiles: 30,
    typicalElevationGainFt: 1000,
    dropPolicy: "No-drop",
    rideSchedule: "Weekly",
    segmentation: "N/A",
    howToJoin: "Open to all: introduce yourself at our monthly meetup ride.",
    tags: ["women", "road", "community", "beginner-friendly"],
    missionStatement: "Build confidence and community for women on bikes, from first ride to first race.",
    overrides: {
      personaRestrictions: ["Women Only"],
      eventTypes: ["Public Events", "Recruiting Events"],
      social: { instagram: "@rosecitywomenscycling" },
    },
  }),

  makeTeam({
    id: "bay-area-pride-peloton",
    name: "Bay Area Pride Peloton",
    type: "Group Ride",
    location: "San Francisco, CA",
    founded: 2020,
    bikeType: "Mixed",
    format: "In-person",
    pace: "Casual",
    skillLevel: "Beginner",
    competitiveOrCasual: "Casual",
    memberCount: 95,
    typicalDistanceMiles: 22,
    typicalElevationGainFt: 900,
    dropPolicy: "No-drop",
    rideSchedule: "Weekly",
    segmentation: "N/A",
    howToJoin: "Everyone welcome; check our Instagram for the next meetup spot.",
    tags: ["lgbt", "inclusive", "social", "beginner-friendly"],
    missionStatement: "A safe, joyful space to ride for LGBTQ+ cyclists and allies of every level.",
    overrides: {
      personaRestrictions: ["LGBT Only"],
      social: { instagram: "@bayareapridepeloton" },
    },
  }),

  makeTeam({
    id: "motor-city-messengers",
    name: "Motor City Messengers",
    type: "Group Ride",
    location: "Detroit, MI",
    founded: 2013,
    bikeType: "Road",
    format: "In-person",
    pace: "Casual",
    skillLevel: "Beginner",
    competitiveOrCasual: "Casual",
    memberCount: 54,
    typicalDistanceMiles: 15,
    typicalElevationGainFt: 200,
    dropPolicy: "No-drop",
    rideSchedule: "Weekly",
    segmentation: "N/A",
    howToJoin: "Roll up to the Friday night meetup; lights required after dark.",
    tags: ["urban", "commuter", "night rides", "social"],
    overrides: {
      startTimes: ["Fri 8:00 PM"],
    },
  }),

  makeTeam({
    id: "piedmont-elite-development-team",
    name: "Piedmont Elite Development Team",
    type: "Team",
    location: "Greenville, SC",
    founded: 2012,
    bikeType: "Road",
    format: "In-person",
    pace: "Competitive",
    skillLevel: "Advanced",
    competitiveOrCasual: "Competitive",
    memberCount: 30,
    typicalDistanceMiles: 50,
    typicalElevationGainFt: 3200,
    dropPolicy: "Drop",
    rideSchedule: "Weekly",
    segmentation: "A Group",
    howToJoin: "Junior racers are scouted through regional results and by tryout.",
    tags: ["junior", "development", "road", "racing", "competitive"],
    missionStatement: "Develop the Southeast's next generation of elite road racers.",
    overrides: {
      ageRequirement: { max: 23 },
      requiredRaces: 10,
      requiredKit: true,
      duesRequired: true,
      duesAmount: "$300/year",
      duesSchedule: "Annually",
      sponsors: ["Piedmont Bike Co.", "SC Sports Medicine"],
      joinRequirements: { tryouts: true, referralRequired: false, inviteOnly: false, open: false },
      eventTypes: ["Team-specific Events", "Sponsor Events"],
    },
  }),

  makeTeam({
    id: "cascade-family-cruisers",
    name: "Cascade Family Cruisers",
    type: "Club",
    location: "Seattle, WA",
    founded: 2019,
    bikeType: "Mixed",
    format: "In-person",
    pace: "Casual",
    skillLevel: "Beginner",
    competitiveOrCasual: "Casual",
    memberCount: 110,
    typicalDistanceMiles: 8,
    typicalElevationGainFt: 150,
    dropPolicy: "No-drop",
    rideSchedule: "Weekly",
    segmentation: "N/A",
    howToJoin: "Bring the whole family to any Saturday morning ride; trailers and kid bikes welcome.",
    tags: ["family-friendly", "kids-ok", "weekend", "social", "beginner-friendly"],
    overrides: {
      ageRequirement: { min: 8 },
      social: { facebook: "CascadeFamilyCruisers" },
      verified: false,
      lastActiveYear: 2024,
    },
  }),

  makeTeam({
    id: "sonoran-desert-endurance-club",
    name: "Sonoran Desert Endurance Club",
    type: "Club",
    location: "Phoenix, AZ",
    founded: 2010,
    bikeType: "Gravel",
    format: "In-person",
    pace: "Steady",
    skillLevel: "Intermediate",
    competitiveOrCasual: "Casual",
    memberCount: 64,
    typicalDistanceMiles: 55,
    typicalElevationGainFt: 2800,
    dropPolicy: "No-drop",
    rideSchedule: "Weekly",
    segmentation: "B Group",
    howToJoin: "Early risers welcome; meet at the trailhead before sunrise heat sets in.",
    tags: ["gravel", "endurance", "desert", "early-morning"],
    overrides: {
      startTimes: ["Sat 5:30 AM"],
    },
  }),

  makeTeam({
    id: "green-mountain-brevet-society",
    name: "Green Mountain Brevet Society",
    type: "Organization",
    location: "Burlington, VT",
    founded: 2005,
    bikeType: "Road",
    format: "In-person",
    pace: "Steady",
    skillLevel: "Advanced",
    competitiveOrCasual: "Casual",
    memberCount: 48,
    typicalDistanceMiles: 120,
    typicalElevationGainFt: 6000,
    dropPolicy: "No-drop",
    rideSchedule: "Monthly",
    segmentation: "N/A",
    howToJoin: "Register for a permanent brevet route through Randonneurs USA.",
    tags: ["randonneuring", "brevet", "long-distance", "endurance"],
    missionStatement: "Preserve and promote long-distance unsupported randonneuring in the Green Mountains.",
    overrides: {
      affiliation: "Randonneurs USA, Vermont Chapter",
      requiredRides: true,
      mileageRequirement: { min: 200, frequency: "Monthly" },
      verified: false,
      lastActiveYear: 2024,
    },
  }),

  makeTeam({
    id: "chicago-lakefront-cruisers",
    name: "Chicago Lakefront Cruisers",
    type: "Club",
    location: "Chicago, IL",
    founded: 2016,
    bikeType: "Road",
    format: "In-person",
    pace: "Casual",
    skillLevel: "Beginner",
    competitiveOrCasual: "Casual",
    memberCount: 132,
    typicalDistanceMiles: 18,
    typicalElevationGainFt: 100,
    dropPolicy: "No-drop",
    rideSchedule: "Weekly",
    segmentation: "N/A",
    howToJoin: "Meet at Monroe Harbor any Wednesday evening, no drop, no stress.",
    tags: ["casual", "scenic", "beginner-friendly", "social"],
    overrides: {
      startTimes: ["Wed 6:30 PM"],
    },
  }),

  makeTeam({
    id: "twin-cities-gravel-collective",
    name: "Twin Cities Gravel Collective",
    type: "Group Ride",
    location: "Minneapolis, MN",
    founded: 2018,
    bikeType: "Gravel",
    format: "In-person",
    pace: "Steady",
    skillLevel: "Intermediate",
    competitiveOrCasual: "Casual",
    memberCount: 64,
    typicalDistanceMiles: 38,
    typicalElevationGainFt: 900,
    dropPolicy: "No-drop",
    rideSchedule: "Weekly",
    segmentation: "N/A",
    howToJoin: "Join the Discord for weekly route drops and meetup points.",
    tags: ["gravel", "social", "midwest"],
    overrides: {
      social: { discord: "discord.gg/tcgravel" },
    },
  }),

  makeTeam({
    id: "rocky-mountain-junior-racers",
    name: "Rocky Mountain Junior Racers",
    type: "Youth Program",
    location: "Denver, CO",
    founded: 2014,
    bikeType: "Road",
    format: "In-person",
    pace: "Competitive",
    skillLevel: "Intermediate",
    competitiveOrCasual: "Competitive",
    memberCount: 38,
    typicalDistanceMiles: 25,
    typicalElevationGainFt: 1400,
    dropPolicy: "Drop",
    rideSchedule: "Weekly",
    segmentation: "B Group",
    howToJoin: "Parents can enroll junior riders through our season sign-up form each spring.",
    tags: ["junior", "development", "coached", "road", "racing"],
    missionStatement: "Coach junior riders ages 12-18 into confident, competitive racers.",
    overrides: {
      ageRequirement: { min: 12, max: 18 },
      instructional: true,
      requiredKit: true,
      sponsors: ["Rocky Mountain Bike Shop"],
      eventTypes: ["Team-specific Events", "Public Events"],
    },
  }),

  makeTeam({
    id: "alamo-city-tri-club",
    name: "Alamo City Tri Club",
    type: "Club",
    location: "San Antonio, TX",
    founded: 2016,
    bikeType: "Tri",
    format: "In-person",
    pace: "Casual",
    skillLevel: "Beginner",
    competitiveOrCasual: "Casual",
    memberCount: 71,
    typicalDistanceMiles: 24,
    typicalElevationGainFt: 300,
    dropPolicy: "No-drop",
    rideSchedule: "Weekly",
    segmentation: "N/A",
    howToJoin: "Se habla español. Join any Saturday clinic to meet the club.",
    tags: ["triathlon", "bilingual", "beginner-friendly", "coached"],
    overrides: {
      instructional: true,
      primaryLanguage: "English & Spanish",
    },
  }),

  makeTeam({
    id: "brooklyn-fixed-gear-crew",
    name: "Brooklyn Fixed Gear Crew",
    type: "Group Ride",
    location: "Brooklyn, NY",
    founded: 2012,
    bikeType: "Track",
    format: "In-person",
    pace: "Steady",
    skillLevel: "Intermediate",
    competitiveOrCasual: "Casual",
    memberCount: 46,
    typicalDistanceMiles: 12,
    typicalElevationGainFt: 50,
    dropPolicy: "Drop",
    rideSchedule: "Weekly",
    segmentation: "N/A",
    howToJoin: "Find us through Instagram; fixed gear only, brakes recommended but not required.",
    tags: ["fixed-gear", "urban", "alleycat", "night-rides", "social"],
    overrides: {
      startTimes: ["Fri 9:00 PM"],
      social: { instagram: "@bkfixedcrew" },
      verified: false,
      lastActiveYear: 2023,
    },
  }),

  makeTeam({
    id: "golden-gate-e-bike-adventurers",
    name: "Golden Gate E-Bike Adventurers",
    type: "Group Ride",
    location: "San Francisco, CA",
    founded: 2022,
    bikeType: "E-bike",
    format: "In-person",
    pace: "Steady",
    skillLevel: "Beginner",
    competitiveOrCasual: "Casual",
    memberCount: 40,
    typicalDistanceMiles: 26,
    typicalElevationGainFt: 2200,
    dropPolicy: "No-drop",
    rideSchedule: "Weekly",
    segmentation: "N/A",
    howToJoin: "RSVP through Meetup; rental e-bikes available for first-timers.",
    tags: ["e-bike", "hills", "adventure", "beginner-friendly"],
    overrides: {
      ageRequirement: { min: 16 },
    },
  }),

  makeTeam({
    id: "peachtree-road-racing-club",
    name: "Peachtree Road Racing Club",
    type: "Club",
    location: "Atlanta, GA",
    founded: 2008,
    bikeType: "Road",
    format: "In-person",
    pace: "Competitive",
    skillLevel: "Advanced",
    competitiveOrCasual: "Competitive",
    memberCount: 58,
    typicalDistanceMiles: 48,
    typicalElevationGainFt: 2600,
    dropPolicy: "Drop",
    rideSchedule: "Weekly",
    segmentation: "A Group",
    howToJoin: "New members complete a graded ride before being added to the roster.",
    tags: ["road", "racing", "competitive", "climbing"],
    overrides: {
      memberLimit: 65,
      waitlist: true,
      duesRequired: true,
      duesAmount: "$120/year",
      duesSchedule: "Annually",
      requiredKit: true,
      website: "https://peachtreeracing.example.org",
    },
  }),

  makeTeam({
    id: "research-triangle-trainerroad-squad",
    name: "Research Triangle TrainerRoad Squad",
    type: "Team",
    location: "Raleigh, NC",
    founded: 2020,
    bikeType: "Road",
    format: "Hybrid",
    pace: "Competitive",
    skillLevel: "Advanced",
    competitiveOrCasual: "Competitive",
    memberCount: 52,
    typicalDistanceMiles: 35,
    typicalElevationGainFt: 1600,
    dropPolicy: "Drop",
    rideSchedule: "Weekly",
    segmentation: "A Group",
    howToJoin: "Share a recent TrainerRoad FTP test to be matched to the right group.",
    tags: ["virtual", "structured-training", "winter-training", "road"],
    overrides: {
      virtualPlatform: "TrainerRoad",
      homeBaseAffiliation: "TrainerRoad Team League",
    },
  }),

  makeTeam({
    id: "emerald-city-beginners-club",
    name: "Emerald City Beginners Club",
    type: "Club",
    location: "Seattle, WA",
    founded: 2021,
    bikeType: "Road",
    format: "In-person",
    pace: "Casual",
    skillLevel: "Beginner",
    competitiveOrCasual: "Casual",
    memberCount: 84,
    typicalDistanceMiles: 15,
    typicalElevationGainFt: 400,
    dropPolicy: "No-drop",
    rideSchedule: "Weekly",
    segmentation: "N/A",
    howToJoin: "Built for first-time group riders; no experience or gear judgment, ever.",
    tags: ["beginner-friendly", "instructional", "no-drop", "social"],
    missionStatement: "Teach brand-new riders group-riding skills in a truly no-drop, no-judgment space.",
    overrides: {
      instructional: true,
    },
  }),

  makeTeam({
    id: "high-country-tandem-and-adaptive-riders",
    name: "High Country Tandem & Adaptive Riders",
    type: "Organization",
    location: "Asheville, NC",
    founded: 2017,
    bikeType: "Mixed",
    format: "In-person",
    pace: "Casual",
    skillLevel: "Beginner",
    competitiveOrCasual: "Casual",
    memberCount: 52,
    typicalDistanceMiles: 14,
    typicalElevationGainFt: 500,
    dropPolicy: "No-drop",
    rideSchedule: "Weekly",
    segmentation: "N/A",
    howToJoin: "Contact us directly; we match riders and pilots based on needs and equipment.",
    tags: ["adaptive", "inclusive", "tandem", "accessible"],
    missionStatement: "Make group cycling genuinely accessible for riders of all abilities.",
    overrides: {
      contact: { email: "info@hcadaptive.example.org", phone: "828-555-0199" },
    },
  }),

  makeTeam({
    id: "motown-masters-racing-team",
    name: "Motown Masters Racing Team",
    type: "Team",
    location: "Detroit, MI",
    founded: 2006,
    bikeType: "Road",
    format: "In-person",
    pace: "Competitive",
    skillLevel: "Advanced",
    competitiveOrCasual: "Competitive",
    memberCount: 34,
    typicalDistanceMiles: 42,
    typicalElevationGainFt: 1100,
    dropPolicy: "Drop",
    rideSchedule: "Weekly",
    segmentation: "A Group",
    howToJoin: "Masters (35+) racers can request an invite after a race season together.",
    tags: ["masters", "road", "racing", "competitive"],
    overrides: {
      ageRequirement: { min: 35 },
      requiredRaces: 8,
      requiredKit: true,
      duesRequired: true,
      duesAmount: "$180/year",
      duesSchedule: "Annually",
      joinRequirements: { tryouts: false, referralRequired: false, inviteOnly: true, open: false },
    },
  }),

  makeTeam({
    id: "blue-ridge-bikepacking-society",
    name: "Blue Ridge Bikepacking Society",
    type: "Group Ride",
    location: "Asheville, NC",
    founded: 2019,
    bikeType: "Gravel",
    format: "In-person",
    pace: "Steady",
    skillLevel: "Intermediate",
    competitiveOrCasual: "Casual",
    memberCount: 36,
    typicalDistanceMiles: 80,
    typicalElevationGainFt: 5200,
    dropPolicy: "No-drop",
    rideSchedule: "Monthly",
    segmentation: "N/A",
    howToJoin: "Join the group chat before your first overnight trip to coordinate gear.",
    tags: ["bikepacking", "adventure", "overnight", "gravel"],
    overrides: {
      social: { instagram: "@blueridgebikepacking" },
    },
  }),

  makeTeam({
    id: "silicon-valley-strava-club",
    name: "Silicon Valley Strava Club",
    type: "Club",
    location: "San Jose, CA",
    founded: 2015,
    bikeType: "Road",
    format: "Hybrid",
    pace: "Steady",
    skillLevel: "Intermediate",
    competitiveOrCasual: "Casual",
    memberCount: 210,
    typicalDistanceMiles: 30,
    typicalElevationGainFt: 1300,
    dropPolicy: "No-drop",
    rideSchedule: "Weekly",
    segmentation: "N/A",
    howToJoin: "Join our Strava club online, then come out to any weekend ride in person.",
    tags: ["strava", "virtual-plus-irl", "kom-hunting", "tech industry"],
    overrides: {
      virtualPlatform: "Strava",
      social: { strava: "Silicon Valley Strava Club" },
    },
  }),
];

export function getAllTeams(): Team[] {
  return teams;
}

export function getTeamById(id: string): Team | undefined {
  return teams.find((team) => team.id === id);
}
